### ISSUE TITLE
Products list page, the note is no limited of words so affect other field like price, see screenshot.

### ISSUE THREAD

**Issue by Kingwayer** [invoiceninja/ui#1851]
referring to screenshot.

![image](https://github.com/invoiceninja/dockerfiles/assets/171299849/f7374376-235c-4c99-a20d-2f9d41e71638)

**Setup information**

docker run / docker-compose / Helm

**Describe the bug**

**To reproduce**

**Expected behavior**

**Screenshots/logs**

```
Any Error that sucks
```

**Docker/Kubernetes/Helm**:
- Output of `docker version`:
```
(paste your output here)
```

- Output of `helm version`:
```
(paste your output here)
```
- Output of `kubectl version`:
```
(paste your output here)
```

**Additional context**

**Comment by Civolilah** [comment]
@turbo124 I succeeded in recreating this bug by removing the part of the logic that was recently updated. The bug is actually already resolved, I believe that it's just not on the `main` branch yet. Here's a screenshot without the recently updated logic:

![Screenshot 2024-07-25 at 14 11 10](https://github.com/user-attachments/assets/3f4c1734-38b0-49d0-a1eb-6acc60453673)

Screenshot with recently updated logic:

![Screenshot 2024-07-25 at 14 11 38](https://github.com/user-attachments/assets/0bfe0488-ef37-47eb-a3af-90289ec01b31)

I think that we can close this issue.
