### ISSUE TITLE
URLs are broken in production environments

### ISSUE THREAD

**Issue by itkfm** [invoiceninja/ui#199]
*Version: v5.5.6-C89 (according to the Flutter frontend)*

Refreshing the page in the browser does not work as expected.

### Expected result

- I can hit refresh just fine.
- I can share working links with my workmates. (The Flutter frontend misses this feature in the first place)

### Actual result

You’ll end up with an error 404 page.

Seems like those routes aren’t registered to be handled by the frontend.
I’d suggest doing either:
- Redirect those routes to the frontend
- Don’t use the PushState API

<details>
<summary>

### Screenshot

</summary>

![image](https://user-images.githubusercontent.com/53079668/188832320-dee273bd-91a1-4963-96e7-cc72d246790a.png)

</details>

**Comment by turbo124** [comment]
We've had this raised before, but I am unable to recreate this particular issue when using Nginx as the webserver.


My gut here is telling me that there are two possible issues:

1. Systems using Apache may not be parsing the # sign correctly via the .htaccess which is then sending the request to PHP rather than index.html
2. index.php is being preferenced BEFORE index index.html and hence all refresh requests are being routed to index.php

**Comment by itkfm** [comment]
Our setup pretty much resembles the sample provided by https://invoiceninja.github.io/docs/self-host-installation/

**Comment by turbo124** [comment]
If you nginx configuration can you reorder this line

```
index index.php index.html index.htm;
```

to look like this:
```
index index.html index.htm index.php ;
```

restart nginx and then advise if the problem persists please.

**Comment by itkfm** [comment]
issue persists (as expected, because an URI like '/tasks` won’t be handled by index)

**Comment by itkfm** [comment]
what’s more? there isn’t even an `index.html`…

**Comment by turbo124** [comment]
@itkfm 

Ah, I think I understand why I haven't seen this previously.

We don't package the index.html in the builds as it may be preferenced by the webserver. Instead we switch to react within the application itself which may well explain what you are seeing.
