### ISSUE TITLE
'Payment failed' email template listed twice in drop-down menu in React

### ISSUE THREAD

**Issue by StrangePeanut** [invoiceninja/ui#2147]
## Setup

- Version: 5.10.35
- Environment: Other

## Checklist

- Can you replicate the issue on our v5 demo site https://demo.invoiceninja.com or https://react.invoicing.co/demo? Yes
- Have you searched existing issues? Yes

## Describe the bug

The 'Payment failed' email template is listed twice in the template drop-down menu in the React app

### Steps To Reproduce

Open the template drop-down menu under template and reminders settings in the React app

### Expected Behaviour

The 'Payment failed' email template is listed once

**Comment by Civolilah** [comment]
@StrangePeanut @turbo124 The issue has actually already been fixed, but it's still persisting in production because we haven't released the fix yet. It will be fixed in the production environment with the next release. Here's a screenshot from development:

<img width="812" alt="Screenshot 2024-12-03 at 17 28 38" src="https://github.com/user-attachments/assets/1e5465b2-c354-4edc-8eca-073a59c67823">
